apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
    providers:
      - kms:
          name: myKmsPlugin
          endpoint: unix:///opt/cloudadm/kubernetes-vault-kms-plugin/vault/server/test
          cachesize: 100
          timeout: 3s
      - identity: {}
