
# This manifest is used to deploy an httpgo deployment and to deploy its service.
# The image ttedesch/httpgo_exporter:latest contains an httpgo server and a process exporter that looks for httpgo process

# create service
apiVersion: v1
kind: Service
metadata:
  name: httpgo
spec:
  type: NodePort 
  selector:
    app: httpgo
  ports:
  - port: 8888
    targetPort: 8888 
    protocol: TCP
    name: http
    nodePort: 31000
---
# create httpgo (with exporter) deployment
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: httpgo
spec:
  selector:
    matchLabels:
      app: httpgo
  replicas: 1
  template:
    metadata:
      labels:
        app: httpgo
    spec:
      containers:
      - name: httpgo
        image: veknet/httpgo:latest
        ports:
        - containerPort: 8888
        imagePullPolicy: Always
