# create service
apiVersion: v1
kind: Service
metadata:
  name: httpgo
spec:
  type: NodePort 
  selector:
    app: httpgo
  ports:
  - port: 8888
    targetPort: 8888 
    protocol: TCP
    name: http
    nodePort: 31000
---
# create httpgo deployment
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: httpgo
spec:
  selector:
    matchLabels:
      app: httpgo
  replicas: 1
  template:
    metadata:
      labels:
        app: httpgo
    spec:
      containers:
      - name: httpgo
        #image: veknet/httpgo:latest
        image: registry.cern.ch/cmsweb/httpgo@sha256:50b8811b2b9bb834457a0764c8277b6d7242a3eba0d1b76fcbbeb7f12392ab56
        command: ["/data/httpgo"]
        args: ["-config", "/etc/config/httpgoConfig.json"]
        #-config /etc/config/httpgoConfig.json  
        volumeMounts:
          - mountPath: "/etc/certs/"
            name: my-tls-secret
            readOnly: true
          - mountPath: "/etc/config"
            name: config-volume
        ports:
        - containerPort: 8888
        imagePullPolicy: Always
      volumes:
        - name: my-tls-secret
          secret:
            secretName: my-tls-secret
          volumes:
        - name: config-volume
          configMap:
            name: httpgo-config
